### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by neverstoplearn** [wenyu332/daguan_bert_ner#18]
Traceback (most recent call last):
  File "main.py", line 234, in <module>
    train()
  File "main.py", line 26, in train
    train_data,_ = read_corpus(args.pretrain_train_path, max_length=args.max_seq_length, label_dic=label_dic, vocab=vocab)
  File "/home/wuwenfu/daguan_bert_ner-master/utils.py", line 83, in read_corpus
    assert len(label_ids) == max_length
AssertionError

你好 请问这种错误是什么原因，非常感谢？

**Comment by wenyu332** [comment]
标签长度不等于设置的每个句子的最大错误，你打印一下每个样本的标签长度，然后和设置的最大长度比较一下，找出错误的句子，看看是什么原因，然后修改一下即可。 我这里写的是没什么错误，猜测是你直接用了提交的预测样本来做，那个里面没有对应的标签信息，所以长度为0.
